"""phase5_extend_patient_referrals_careteams

Revision ID: 9b76f373fc10
Revises: 9cb53e30d274
Create Date: 2026-03-06 01:34:44.517854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b76f373fc10'
down_revision: Union[str, Sequence[str], None] = '9cb53e30d274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('patient_profiles', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('patient_profiles', sa.Column('preferred_language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('patient_profiles', sa.Column('allergies', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('chronic_conditions', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('past_surgeries', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('patient_profiles', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('patient_profiles', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('patient_profiles', sa.Column('blood_pressure', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('patient_profiles', sa.Column('insurance_provider', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('patient_profiles', sa.Column('insurance_policy_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('patient_profiles', sa.Column('insurance_group_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('patient_profiles', sa.Column('address_street', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('patient_profiles', sa.Column('address_city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('patient_profiles', sa.Column('address_state', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('patient_profiles', sa.Column('address_zip', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('patient_profiles', sa.Column('address_country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'address_country')
    op.drop_column('patient_profiles', 'address_zip')
    op.drop_column('patient_profiles', 'address_state')
    op.drop_column('patient_profiles', 'address_city')
    op.drop_column('patient_profiles', 'address_street')
    op.drop_column('patient_profiles', 'insurance_group_number')
    op.drop_column('patient_profiles', 'insurance_policy_number')
    op.drop_column('patient_profiles', 'insurance_provider')
    op.drop_column('patient_profiles', 'blood_pressure')
    op.drop_column('patient_profiles', 'weight_kg')
    op.drop_column('patient_profiles', 'height_cm')
    op.drop_column('patient_profiles', 'past_surgeries')
    op.drop_column('patient_profiles', 'chronic_conditions')
    op.drop_column('patient_profiles', 'allergies')
    op.drop_column('patient_profiles', 'preferred_language')
    op.drop_column('patient_profiles', 'phone')
    op.drop_column('patient_profiles', 'gender')
    # ### end Alembic commands ###
