"""add_name_image_authprovider_to_users

Revision ID: 9cb53e30d274
Revises: 110915e13b4f
Create Date: 2026-03-04 21:54:34.422762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9cb53e30d274'
down_revision: Union[str, Sequence[str], None] = '110915e13b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add `name` as nullable first so existing rows don't break,
    # backfill them with a placeholder, then enforce NOT NULL.
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.execute("UPDATE users SET name = split_part(email, '@', 1) WHERE name IS NULL")
    op.alter_column('users', 'name', nullable=False)
    op.add_column('users', sa.Column('image', sa.String(length=1024), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), server_default=sa.text("'credentials'"), nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'image')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
